In [1]:
!pip install jupyterthemes

In [4]:
!jt -l

Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl


In [6]:
!jt -t oceans16

# simple python code

In [12]:
a=5

In [13]:
b=10

In [14]:
a*b


50

In [15]:
a+b

15

In [16]:
a/b

0.5

In [17]:
a-b

-5

In [18]:
type(a/b)

float

In [19]:
type(a-b)

int

In [20]:
a="sdth"

In [21]:
print(a)

sdth


In [22]:
type(a)

str

In [23]:
b=True

In [24]:
type(b)

bool

# relational operator

In [27]:
c=30
d=25

In [28]:
c>d


True

In [29]:
c==d

False

In [30]:
c!=d

True

In [31]:
a=True
b=False

In [32]:
a&b

False

In [33]:
b&a

False

In [34]:
b&b

False

In [35]:
a&a

True

In [36]:
a|b

True

In [37]:
b|a

True

In [38]:
a|a

True

In [39]:
b|b

False

In [40]:
#string

In [41]:
name="my name is john"

In [42]:
name[5]

'm'

In [43]:
name[4:8]

'ame '

In [44]:
name[5:10]

'me is'

In [45]:
name[-1]

'n'

In [46]:
name[-4:-8]

''

In [47]:
name.upper()

'MY NAME IS JOHN'

In [48]:
name.lower()

'my name is john'

In [49]:
len(name)

15

In [50]:
name.replace('y','a')

'ma name is john'

# welcome to jupyter notebook

In [51]:
print(complex(2,6))

(2+6j)


In [52]:
x=2.5

In [53]:
print(abs(x))

2.5


In [54]:
import math
x=10
print(math.exp(x))

22026.465794806718


In [55]:
math.e

2.718281828459045

In [56]:
math.pi

3.141592653589793

In [57]:
print(math.sqrt(6))

2.449489742783178


# LISTS

In [58]:
num=[12,35,24,48]

In [59]:
print(num)

[12, 35, 24, 48]


In [60]:
letter=['a','b','d','r']
print(letter)

['a', 'b', 'd', 'r']


In [61]:
stg=['get','string','nine','for']
print(stg)

['get', 'string', 'nine', 'for']


In [62]:
mix=[1,7,'nine','string','certified']

In [63]:
print(mix)

[1, 7, 'nine', 'string', 'certified']


In [64]:
net=[[1,5,6],'nine','met',['a',4,'$']]

In [65]:
print(net)

[[1, 5, 6], 'nine', 'met', ['a', 4, '$']]


In [66]:
net[2]

'met'

In [67]:
net[0:3]

[[1, 5, 6], 'nine', 'met']

In [68]:
net[:-3]

[[1, 5, 6]]

In [69]:
net[::5]

[[1, 5, 6]]

In [70]:
net[::-1]

[['a', 4, '$'], 'met', 'nine', [1, 5, 6]]

# operations on a list

In [71]:
z=[0]*100

In [72]:
print(z)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [73]:
print(letter)

['a', 'b', 'd', 'r']


In [74]:
conc=letter+net
print(conc)

['a', 'b', 'd', 'r', [1, 5, 6], 'nine', 'met', ['a', 4, '$']]


In [75]:
var=list("hey there")
print(var)

['h', 'e', 'y', ' ', 't', 'h', 'e', 'r', 'e']


In [76]:
print(num)

[12, 35, 24, 48]


In [77]:
one,*other=num
print(one)
print(other)

12
[35, 24, 48]


# methods in lists

In [78]:
print(num)

[12, 35, 24, 48]


In [79]:
num.append(9)
print(num)

[12, 35, 24, 48, 9]


In [80]:
num.extend(stg)

In [81]:
print(num)

[12, 35, 24, 48, 9, 'get', 'string', 'nine', 'for']


In [82]:
num.insert(4,"simplilearn")
print(num)

[12, 35, 24, 48, 'simplilearn', 9, 'get', 'string', 'nine', 'for']


In [83]:
num.remove('simplilearn')

In [84]:
print(num)

[12, 35, 24, 48, 9, 'get', 'string', 'nine', 'for']


In [85]:
var=['a','h','r','e']
var.sort()
print(var)

['a', 'e', 'h', 'r']


# built in functons with lists

In [86]:
x=[12,45,23,45]
len(x)

4

In [87]:
min(x)

12

In [88]:
max(x)

45

In [89]:
sum(x)

125

In [90]:
sum(x)/len(x)

31.25

# TUPLES

In [91]:
no=()

In [92]:
print(type(no))

<class 'tuple'>


In [93]:
print(no)

()


In [94]:
city="new york",
type(city)

tuple

In [95]:
city='surat','noida','lucknow'
city

('surat', 'noida', 'lucknow')

In [96]:
list=[12,45,0,8,13]
tuple=(13,56,89,15,7)
list.append(5)
print(list)

[12, 45, 0, 8, 13, 5]


In [97]:
list.append(tuple)
print(tuple)

(13, 56, 89, 15, 7)


In [98]:
tuple.append(7)

AttributeError: 'tuple' object has no attribute 'append'

In [99]:
city[1]

'noida'

In [103]:
city[-2]

'noida'

In [104]:
city[-3]

'surat'

In [105]:
print(city)

('surat', 'noida', 'lucknow')


In [106]:
num=1,4,6,57

In [107]:
print(city+num)

('surat', 'noida', 'lucknow', 1, 4, 6, 57)


# nesting

In [108]:
nest=(city,num)

In [109]:
print(nest)

(('surat', 'noida', 'lucknow'), (1, 4, 6, 57))


# repetition

In [110]:
rep=("python",)*5

In [111]:
rep

('python', 'python', 'python', 'python', 'python')

# slicing

In [112]:
num

(1, 4, 6, 57)

In [113]:
num[1:]

(4, 6, 57)

In [114]:
num[::-1]

(57, 6, 4, 1)

# unpacking

In [115]:
tuple("simplilearn")

TypeError: 'tuple' object is not callable

In [116]:
a,b,c,d=num

In [117]:
print(num)

(1, 4, 6, 57)


In [118]:
print(a,b,c,d)

1 4 6 57


# built in function

In [119]:
num

(1, 4, 6, 57)

In [120]:
num.count

<function tuple.count(value, /)>

In [121]:
num.count()

TypeError: tuple.count() takes exactly one argument (0 given)

In [122]:
num.count(2)

0

In [123]:
max(num)

57

In [124]:
num

(1, 4, 6, 57)

# converting list to tuple

In [125]:
list=[24,67,12,34]
print(type(list))


<class 'list'>


In [126]:
tpl=tuple(list)
print(tpl)

TypeError: 'tuple' object is not callable

# nesting in tuple

In [127]:
lst=[(1,23,12),(34,13,24)]

In [128]:
print(lst)

[(1, 23, 12), (34, 13, 24)]


In [129]:
lst.append(("tuple",'inside','list'))

In [130]:
print(lst)

[(1, 23, 12), (34, 13, 24), ('tuple', 'inside', 'list')]


In [131]:
lst.remove((1,23,12))

In [132]:
print(lst)

[(34, 13, 24), ('tuple', 'inside', 'list')]


# nesting list within tuple

In [144]:
tpl=(['a','b','c'],['d','e','g'])
print(tpl)

(['a', 'b', 'c'], ['d', 'e', 'g'])


In [145]:
tpl[0].append('z')

In [146]:
print(tpl)

(['a', 'b', 'c', 'z'], ['d', 'e', 'g'])


In [147]:
tpl[0].remove('z')

In [148]:
print(tpl)

(['a', 'b', 'c'], ['d', 'e', 'g'])


# dictionary

In [149]:
d1={}

In [150]:
d1={1:"dahlia",2:"reactangle",3:"sphere"}
print(d1)

{1: 'dahlia', 2: 'reactangle', 3: 'sphere'}


In [151]:
d2={'name':'nisha','roll no':2,'subject':'english'}
print(d2)

{'name': 'nisha', 'roll no': 2, 'subject': 'english'}


In [152]:
type(d2)

dict

In [153]:
d3=dict([(1,"welcome"),(2,"to"),(3,"India")])

In [154]:
print(d3)

{1: 'welcome', 2: 'to', 3: 'India'}


# using built in functtions

In [155]:
d3.values()

dict_values(['welcome', 'to', 'India'])

In [156]:
keys={'a','b','c','d'}
value=1
dict.fromkeys(keys,value)

{'a': 1, 'c': 1, 'b': 1, 'd': 1}

In [157]:
keys={'marks','grade'}
value=25,'e'
d2.fromkeys(keys,value)

{'grade': (25, 'e'), 'marks': (25, 'e')}

In [158]:
print(d2)

{'name': 'nisha', 'roll no': 2, 'subject': 'english'}


# sets

In [159]:
s=set([1,2,3,4])
print(s)
print(type(s))

{1, 2, 3, 4}
<class 'set'>


In [160]:
s.add('a')
print(s)

{1, 2, 3, 4, 'a'}


In [161]:
fs=frozenset([1,2,3,4])
print(fs)

frozenset({1, 2, 3, 4})


# array

In [162]:
cars = ["Ford", "Volvo", "BMW"]

In [163]:
type(cars)

list

In [164]:
print(cars)

['Ford', 'Volvo', 'BMW']


In [165]:
x = cars[0]

In [166]:
print(x)

Ford


In [167]:
len(cars)

3

In [168]:
for x in cars:
  print(x)

Ford
Volvo
BMW


In [169]:
cars.append("Honda")
print(cars)

['Ford', 'Volvo', 'BMW', 'Honda']


In [170]:
cars.pop(1)

'Volvo'

In [171]:
cars.reverse()
print(cars)

['Honda', 'BMW', 'Ford']


In [176]:
import array as arr
arr=array("i",[])
x=int(input("enter the size of array"))
print('enter %d elements'%x)

NameError: name 'array' is not defined

In [177]:
import numpy as np
print (np.version.version)


1.20.3


In [178]:
A=np.array([[12,34,13,4],[23,14,5,67]])
print(A)
print(A.ndim)

[[12 34 13  4]
 [23 14  5 67]]
2


In [179]:
B=np.array([[12,34,6,78],[23,45,8,79]])
print(B)
print(B.ndim)

[[12 34  6 78]
 [23 45  8 79]]
2


In [180]:
sum=A+B
print(sum)

[[ 24  68  19  82]
 [ 46  59  13 146]]


In [181]:
diff=A-B
print(diff)

[[  0   0   7 -74]
 [  0 -31  -3 -12]]


In [182]:
mul=A*B
print(mul)

[[ 144 1156   78  312]
 [ 529  630   40 5293]]


In [183]:
div=A/B
print(div)

[[1.         1.         2.16666667 0.05128205]
 [1.         0.31111111 0.625      0.84810127]]


In [184]:
type(div)

numpy.ndarray

In [185]:
mode=A//B
print(mode)

[[1 1 2 0]
 [1 0 0 0]]


In [186]:
D=np.linalg.inv(A)
print(D)

LinAlgError: Last 2 dimensions of the array must be square

In [187]:
E=np.sqrt(A)
print(E)

[[3.46410162 5.83095189 3.60555128 2.        ]
 [4.79583152 3.74165739 2.23606798 8.18535277]]


# string

In [188]:
h="hello everyone"

In [189]:
print(h)

hello everyone


In [ ]:
name=input("enter a string")

In [ ]:
stg="this is my work"

In [ ]:
print(stg)

In [ ]:
print(stg.upper())
print(stg.lower())
print(stg.find('1'))
print(stg.index('1'))
x=stg.split("")
print(x)
print(stg.replace("work","python"))

In [ ]:
stg1="hey"

In [ ]:
stg2="there"

In [ ]:
stg3="all"

In [ ]:
stg="{} {} {}!".format(stg1,stg2,stg3)